In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Loading Datasets

In [3]:
virtual = pd.read_csv("../../data/virtual_events.csv")
real = pd.read_csv("../../data/real_events.csv")

In [4]:
real.describe()

                id      pt_real       y_real      z_gluon       weight
count  3000.000000  3000.000000  3000.000000  3000.000000  3000.000000
mean   1500.500000    30.073175     0.039401     4.970568     8.561418
std     866.169729    30.170103     1.501202     4.939488     5.290617
min       1.000000     0.005092    -5.092144     0.000462     0.001518
25%     750.750000     8.889415    -0.964459     1.520514     4.156885
50%    1500.500000    20.934712     0.044991     3.454818     8.236984
75%    2250.250000    41.474291     1.103602     6.878433    12.674936
max    3000.000000   278.755791     4.629775    38.782019    23.310711

In [5]:
virtual.describe()

                id           pt            y       weight
count  1500.000000  1500.000000  1500.000000  1500.000000
mean    750.500000    29.667175    -0.050769    -5.040186
std     433.157015    29.408526     1.579329     2.992824
min       1.000000     0.000284    -4.997031   -11.844721
25%     375.750000     8.219215    -1.135975    -7.449911
50%     750.500000    20.260382    -0.034716    -4.966707
75%    1125.250000    42.714615     0.992715    -2.352622
max    1500.000000   224.567861     4.497154    -0.005719

# Born Projection

In [6]:
real["pt"] = real["pt_real"] + real["z_gluon"]
real["y"] = real["y_real"]